---
name: Bakerydemo GOLD v2.0 benchmark
author: Arne Tarra <arne@green-coding.io>
description: Testing all routes of the exemplary Bakery demo Gold v2.0 Benchmark with cache pre-warmed in build step

compose-file: !include docker-compose.yml

sci:
  R_d: page request

services:
  db:
    # we need the DB fully booted. Therefore we wait here a little
    setup-commands:
      - command: sleep 10
    networks:
      - bakery-internal-network

  redis:
    networks:
      - bakery-internal-network

  app:
    environment:
      WAGTAILADMIN_BASE_URL: http://app:8000/admin/
    build:
      context: .
      dockerfile: ./Dockerfile
    shell: bash
    setup-commands:
      - /venv/bin/python manage.py migrate
      - /venv/bin/python manage.py load_initial_data
      - wget --recursive --spider --no-directories http://app:8000/ -o warmup.log || true
       # wget issues an error code 8 due to some images returning 404. We could catch the code 8 specifically, but
        # it would not tell us if these are the known images or some other problems with the sever occured.
        # Sadly this call is very flaky and might still show up as successful even if cache warmup did not really work :(
        # PRs welcome!
    networks:
      - bakery-internal-network

  gcb-playwright:
    image: greencoding/gcb_playwright:v16
    networks:
      - bakery-internal-network

networks:
  bakery-internal-network:
    internal: true

flow:
  - name: Blog filtering
    container: gcb-playwright
    commands:
      - type: console
        command:  USAGE_SCENARIO_DOMAIN=http://app:8000 python3 /tmp/repo/benchmark/playwright/blog-filtering.py
        shell: sh
        log-stdout: True
        read-sci-stdout: True
        read-notes-stdout: True

  - name: Contact Us
    container: gcb-playwright
    commands:
      - type: console
        command:  USAGE_SCENARIO_DOMAIN=http://app:8000 python3 /tmp/repo/benchmark/playwright/contact-us.py
        shell: sh
        log-stdout: True
        read-sci-stdout: True
        read-notes-stdout: True

  - name: Homepage Landing
    container: gcb-playwright
    commands:
      - type: console
        command:  USAGE_SCENARIO_DOMAIN=http://app:8000 python3 /tmp/repo/benchmark/playwright/homepage-landing.py
        shell: sh
        log-stdout: True
        read-sci-stdout: True
        read-notes-stdout: True

  - name: Search
    container: gcb-playwright
    commands:
      - type: console
        command:  USAGE_SCENARIO_DOMAIN=http://app:8000 python3 /tmp/repo/benchmark/playwright/search.py
        shell: sh
        log-stdout: True
        read-sci-stdout: True
        read-notes-stdout: True

  - name: Admin Flow
    container: gcb-playwright
    commands:
      - type: console
        command:  USAGE_SCENARIO_DOMAIN=http://app:8000 python3 /tmp/repo/benchmark/playwright/admin.py
        shell: sh
        log-stdout: True
        read-sci-stdout: True
        read-notes-stdout: True
